name: 'Set up Mill'
description: 'Setup a Mill environment for Scala projects.'
author: 'Jakob Odersky'
inputs:
  mill-version:
    description: 'version of mill to use'
    required: false
    default: '0.8.0'
runs:
  using: 'node12'
  main: 'setup.js'
branding:
  icon: 'box'  
  color: 'red'
